### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ewoutp**
Major update.

Goals:

- Low level connection library 
- High speed
- Fully asynchronous 

TODO

- [x] Fully functional for HTTP+VPack, VST 1.0, VST 1.1. 
- [x] Support for multiple, built-in & custom event loops 
- [x] Look into HTTP implementation. Consider replacing libcurl with a boost::asio based library.
- [x] Remove 3rdparty vendorings. Replace with 'flexible' cmake dependency.

### CODE REVIEW

**Comment by ewoutp** [comment]
@ObiWahn There is a strong belief in boost asio now, so we want to investigate if it is possible to use that for all (including HTTP). 
So using boost asio stuff in the API is no longer considered a problem.

**Comment by ObiWahn** [comment]
We bring our own version of boost. Which might force people to use the same
version even when they do not use asio themselves. That might be a problem
if they want to integrate the driver but prefer a different version.

On Jun 7, 2017 20:10, "Ewout Prangsma" <notifications@github.com> wrote:

@ObiWahn <https://github.com/obiwahn> There is a strong belief in boost
asio now, so we want to investigate if it is possible to use that for all
(including HTTP).
So using boost asio stuff in the API is no longer considered a problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arangodb/fuerte/pull/3#issuecomment-306878732>, or mute
the thread

**Comment by neunhoef** [comment]
Starting to read the source in this form. I will put my comments as I find them here.

**Comment by neunhoef** [comment]
We usually put the `const` keyword behind the thing it makes constant. For example:
const StatusCode StatusOK = 200;
would be
StatusCode const StatusOK = 200;

Here, it does not matter, but in

   char const* x;

and

  char *const y;

the difference is more striking. For the statuscodes, one could think of an enum class as in `lib/Random/RandomGenerator.h` in the main ArangoDB repo?

**Comment by ewoutp** [comment]
Changed `const`, see 12ae6ed1243ddb3d3bcea45c8282aa0d068c77b4

**Comment by ewoutp** [comment]
Got implicit LGTM from @neunhoef due to timeout

**Pull request merged**
