### PR TITLE
Fix #14

### LINKED ISSUE #14: Error on a large request via vst
I use latest master (compiled with gcc-8.2).
```
fuerte/src/vst.cpp:320: void arangodb::fuerte::v1::vst::RequestItem::prepareForNetwork(arangodb::fuerte::v1::vst::VSTVersion, boost::asio::const_buffer, boost::asio::const_buffer): Assertion `chunkIndex <= numChunks' failed.
```
locals from the core dump:
```
chunk = {_chunkLength = 4294967152, _chunkX = 738, _messageID = 4, _messageLength = 11062223, _responseChunkContentOffset = 11062043, _responseContentLength = 140737488339056}
chunkDataLen = 1079
chunkHdrLen = 24
chunkOffset = 9036
msgLength = 11062223
__PRETTY_FUNCTION__ = "void arangodb::fuerte::v1::vst::RequestItem::prepareForNetwork(arangodb::fuerte::v1::vst::VSTVersion, boost::asio::const_buffer, boost::asio::const_buffer)"
numChunks = 369
maxDataLength = 29976
chunkIndex = 370
begin = 0x7fffe65fcb2b ""
end = 0x7fffe65fcb2b ""
remaining = 0
```

### PR DESCRIPTION
**Pull request by dvzubarev**
calculate number of chunks based on real data length.

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @dvzubarev 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by dvzubarev** [comment]
Hi, I have sent signed copy from dvzubarev@yandex.ru

**Comment by OmarAyo** [comment]
Hi @dvzubarev 

Unfortunately, we did not receive any signed CLA. May you try again and send your signed CLA to  cla@arangodb.com

Best,

**Comment by dvzubarev** [comment]
It was merged as part of 832c1149320a77b0bceb20636bd38608c8c5e4fc

**Pull request closed without merging**
